//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_IS.SecretaryView.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hospital_IS.SecretaryView.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string btnAddA {
            get {
                return ResourceManager.GetString("btnAddA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novog korisnika.
        /// </summary>
        internal static string btnAddNewGuest {
            get {
                return ResourceManager.GetString("btnAddNewGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termini.
        /// </summary>
        internal static string btnAppointments {
            get {
                return ResourceManager.GetString("btnAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkaži termin.
        /// </summary>
        internal static string btnCancelAppointment {
            get {
                return ResourceManager.GetString("btnCancelAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        internal static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravi trajni nalog.
        /// </summary>
        internal static string btnCreatePermAccount {
            get {
                return ResourceManager.GetString("btnCreatePermAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        internal static string btnDeleteA {
            get {
                return ResourceManager.GetString("btnDeleteA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši doktora.
        /// </summary>
        internal static string btnDeleteDoctor {
            get {
                return ResourceManager.GetString("btnDeleteDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši obaveštenje.
        /// </summary>
        internal static string btnDeleteNotification {
            get {
                return ResourceManager.GetString("btnDeleteNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši pacijenta.
        /// </summary>
        internal static string btnDeletePatient {
            get {
                return ResourceManager.GetString("btnDeletePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselektuj sve zaposlene.
        /// </summary>
        internal static string btnDeselectAllEpmloyees {
            get {
                return ResourceManager.GetString("btnDeselectAllEpmloyees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselektuj sve pacijente.
        /// </summary>
        internal static string btnDeselectAllPatients {
            get {
                return ResourceManager.GetString("btnDeselectAllPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktori.
        /// </summary>
        internal static string btnDoctors {
            get {
                return ResourceManager.GetString("btnDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitan pregled?.
        /// </summary>
        internal static string btnEmergency {
            get {
                return ResourceManager.GetString("btnEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi grešku.
        /// </summary>
        internal static string btnErrorReport {
            get {
                return ResourceManager.GetString("btnErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gost.
        /// </summary>
        internal static string btnGuest {
            get {
                return ResourceManager.GetString("btnGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjava.
        /// </summary>
        internal static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        internal static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obaveštenja.
        /// </summary>
        internal static string btnNotifications {
            get {
                return ResourceManager.GetString("btnNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijenti.
        /// </summary>
        internal static string btnPatients {
            get {
                return ResourceManager.GetString("btnPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Štampaj.
        /// </summary>
        internal static string btnPrint {
            get {
                return ResourceManager.GetString("btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prostorije.
        /// </summary>
        internal static string btnRooms {
            get {
                return ResourceManager.GetString("btnRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj izmene.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selektuj sve zaposlene.
        /// </summary>
        internal static string btnSelectAllEpmloyees {
            get {
                return ResourceManager.GetString("btnSelectAllEpmloyees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selektuj sve pacijente.
        /// </summary>
        internal static string btnSelectAllPatients {
            get {
                return ResourceManager.GetString("btnSelectAllPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        internal static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poništi sve izmene.
        /// </summary>
        internal static string btnUndo {
            get {
                return ResourceManager.GetString("btnUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni.
        /// </summary>
        internal static string btnUpdateA {
            get {
                return ResourceManager.GetString("btnUpdateA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        internal static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gostujući nalog.
        /// </summary>
        internal static string checkBox {
            get {
                return ResourceManager.GetString("checkBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled.
        /// </summary>
        internal static string ciAppCU {
            get {
                return ResourceManager.GetString("ciAppCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakultet.
        /// </summary>
        internal static string ciCol {
            get {
                return ResourceManager.GetString("ciCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osnovna škola.
        /// </summary>
        internal static string ciElem {
            get {
                return ResourceManager.GetString("ciElem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žensko.
        /// </summary>
        internal static string ciFemale {
            get {
                return ResourceManager.GetString("ciFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srednja škola.
        /// </summary>
        internal static string ciHS {
            get {
                return ResourceManager.GetString("ciHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muško.
        /// </summary>
        internal static string ciMale {
            get {
                return ResourceManager.GetString("ciMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacija.
        /// </summary>
        internal static string ciOper {
            get {
                return ResourceManager.GetString("ciOper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druga.
        /// </summary>
        internal static string druga {
            get {
                return ResourceManager.GetString("druga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoć.
        /// </summary>
        internal static string heHelp {
            get {
                return ResourceManager.GetString("heHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        internal static string heLanguage {
            get {
                return ResourceManager.GetString("heLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacije.
        /// </summary>
        internal static string heOperations {
            get {
                return ResourceManager.GetString("heOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        internal static string heSettings {
            get {
                return ResourceManager.GetString("heSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string heTheme {
            get {
                return ResourceManager.GetString("heTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum:.
        /// </summary>
        internal static string labDate {
            get {
                return ResourceManager.GetString("labDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od:.
        /// </summary>
        internal static string labFrom {
            get {
                return ResourceManager.GetString("labFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do:.
        /// </summary>
        internal static string labUntil {
            get {
                return ResourceManager.GetString("labUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaciji.
        /// </summary>
        internal static string miAbout {
            get {
                return ResourceManager.GetString("miAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna.
        /// </summary>
        internal static string miDark {
            get {
                return ResourceManager.GetString("miDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski jezik.
        /// </summary>
        internal static string miEnglish {
            get {
                return ResourceManager.GetString("miEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoć.
        /// </summary>
        internal static string miHelp {
            get {
                return ResourceManager.GetString("miHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svetla.
        /// </summary>
        internal static string miLight {
            get {
                return ResourceManager.GetString("miLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registruj korisnika.
        /// </summary>
        internal static string miRegistration {
            get {
                return ResourceManager.GetString("miRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži termin.
        /// </summary>
        internal static string miScheduling {
            get {
                return ResourceManager.GetString("miScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski jezik.
        /// </summary>
        internal static string miSerbian {
            get {
                return ResourceManager.GetString("miSerbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži.
        /// </summary>
        internal static string miShow {
            get {
                return ResourceManager.GetString("miShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni.
        /// </summary>
        internal static string miUpdate {
            get {
                return ResourceManager.GetString("miUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prva.
        /// </summary>
        internal static string prva {
            get {
                return ResourceManager.GetString("prva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        internal static string rbInUse {
            get {
                return ResourceManager.GetString("rbInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        internal static string rbNotInUse {
            get {
                return ResourceManager.GetString("rbNotInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosledi svima.
        /// </summary>
        internal static string rbSelectAll {
            get {
                return ResourceManager.GetString("rbSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosledi određenim osobama.
        /// </summary>
        internal static string rbSelectSome {
            get {
                return ResourceManager.GetString("rbSelectSome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istorija pregleda.
        /// </summary>
        internal static string tabAppHistory {
            get {
                return ResourceManager.GetString("tabAppHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledi.
        /// </summary>
        internal static string tabAppointments {
            get {
                return ResourceManager.GetString("tabAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opšte informacije.
        /// </summary>
        internal static string tabGeneral {
            get {
                return ResourceManager.GetString("tabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakazani pregledi.
        /// </summary>
        internal static string tabScheduledApps {
            get {
                return ResourceManager.GetString("tabScheduledApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum kreiranja naloga.
        /// </summary>
        internal static string tbAccCreationDate {
            get {
                return ResourceManager.GetString("tbAccCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja naloga.
        /// </summary>
        internal static string tbAccountSet {
            get {
                return ResourceManager.GetString("tbAccountSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        internal static string tbAddress {
            get {
                return ResourceManager.GetString("tbAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa *.
        /// </summary>
        internal static string tbAddressS {
            get {
                return ResourceManager.GetString("tbAddressS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova vrednost.
        /// </summary>
        internal static string tbAllergenNewValue {
            get {
                return ResourceManager.GetString("tbAllergenNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stara vrednost.
        /// </summary>
        internal static string tbAllergenOldValue {
            get {
                return ResourceManager.GetString("tbAllergenOldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alergije.
        /// </summary>
        internal static string tbAllergies {
            get {
                return ResourceManager.GetString("tbAllergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vreme pregleda.
        /// </summary>
        internal static string tbAppDate {
            get {
                return ResourceManager.GetString("tbAppDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string tbAppDateDG {
            get {
                return ResourceManager.GetString("tbAppDateDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum pregleda.
        /// </summary>
        internal static string tbAppDay {
            get {
                return ResourceManager.GetString("tbAppDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum pregleda *.
        /// </summary>
        internal static string tbAppDS {
            get {
                return ResourceManager.GetString("tbAppDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje pregleda.
        /// </summary>
        internal static string tbAppDuration {
            get {
                return ResourceManager.GetString("tbAppDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje pregleda *.
        /// </summary>
        internal static string tbAppDurationS {
            get {
                return ResourceManager.GetString("tbAppDurationS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledi.
        /// </summary>
        internal static string tbApps {
            get {
                return ResourceManager.GetString("tbApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termini koje je potrebno pomeriti:.
        /// </summary>
        internal static string tbAppsToMove {
            get {
                return ResourceManager.GetString("tbAppsToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme.
        /// </summary>
        internal static string tbAppTimeDG {
            get {
                return ResourceManager.GetString("tbAppTimeDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početak pregleda *.
        /// </summary>
        internal static string tbAppTS {
            get {
                return ResourceManager.GetString("tbAppTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip pregleda.
        /// </summary>
        internal static string tbAppType {
            get {
                return ResourceManager.GetString("tbAppType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip pregleda *.
        /// </summary>
        internal static string tbAppTypeS {
            get {
                return ResourceManager.GetString("tbAppTypeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja.
        /// </summary>
        internal static string tbBirthDate {
            get {
                return ResourceManager.GetString("tbBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja *.
        /// </summary>
        internal static string tbBirthDateS {
            get {
                return ResourceManager.GetString("tbBirthDateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da otkažete termin?.
        /// </summary>
        internal static string tbCancelApp {
            get {
                return ResourceManager.GetString("tbCancelApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da uklonite alergen?.
        /// </summary>
        internal static string tbDeleteAllergen {
            get {
                return ResourceManager.GetString("tbDeleteAllergen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da obrišete doktora? Nakon brisanja doktor se više ne može povratiti..
        /// </summary>
        internal static string tbDeleteDoctor {
            get {
                return ResourceManager.GetString("tbDeleteDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da obrišete obaveštenje?.
        /// </summary>
        internal static string tbDeleteNotification {
            get {
                return ResourceManager.GetString("tbDeleteNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string tbDetails {
            get {
                return ResourceManager.GetString("tbDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktor.
        /// </summary>
        internal static string tbDoctor {
            get {
                return ResourceManager.GetString("tbDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktor *.
        /// </summary>
        internal static string tbDoctorS {
            get {
                return ResourceManager.GetString("tbDoctorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavljen.
        /// </summary>
        internal static string tbDone {
            get {
                return ResourceManager.GetString("tbDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivo obrazovanja.
        /// </summary>
        internal static string tbEducation {
            get {
                return ResourceManager.GetString("tbEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string tbEmail {
            get {
                return ResourceManager.GetString("tbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email *.
        /// </summary>
        internal static string tbEmailS {
            get {
                return ResourceManager.GetString("tbEmailS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslodavac.
        /// </summary>
        internal static string tbEmployeer {
            get {
                return ResourceManager.GetString("tbEmployeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaposleni.
        /// </summary>
        internal static string tbEmployees {
            get {
                return ResourceManager.GetString("tbEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina opreme.
        /// </summary>
        internal static string tbEqipQuantity {
            get {
                return ResourceManager.GetString("tbEqipQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip opreme.
        /// </summary>
        internal static string tbEqipType {
            get {
                return ResourceManager.GetString("tbEqipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        internal static string tbEquipName {
            get {
                return ResourceManager.GetString("tbEquipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprat.
        /// </summary>
        internal static string tbFloorNum {
            get {
                return ResourceManager.GetString("tbFloorNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pol.
        /// </summary>
        internal static string tbGender {
            get {
                return ResourceManager.GetString("tbGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pol *.
        /// </summary>
        internal static string tbGenderS {
            get {
                return ResourceManager.GetString("tbGenderS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opšta podešavanja.
        /// </summary>
        internal static string tbGeneralSet {
            get {
                return ResourceManager.GetString("tbGeneralSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolnica Zdravo.
        /// </summary>
        internal static string tbHospital {
            get {
                return ResourceManager.GetString("tbHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soba je trenutno u upotrebi.
        /// </summary>
        internal static string tbIsInUse {
            get {
                return ResourceManager.GetString("tbIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        internal static string tbLanguage {
            get {
                return ResourceManager.GetString("tbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string tbName {
            get {
                return ResourceManager.GetString("tbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime *.
        /// </summary>
        internal static string tbNameS {
            get {
                return ResourceManager.GetString("tbNameS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponovite šifru.
        /// </summary>
        internal static string tbPasswordConfS {
            get {
                return ResourceManager.GetString("tbPasswordConfS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra *.
        /// </summary>
        internal static string tbPasswordS {
            get {
                return ResourceManager.GetString("tbPasswordS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent.
        /// </summary>
        internal static string tbPatient {
            get {
                return ResourceManager.GetString("tbPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da obrišete pacijenta? Nakon brisanja pacijent se više ne može povratiti..
        /// </summary>
        internal static string tbPatientDelete {
            get {
                return ResourceManager.GetString("tbPatientDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijenti.
        /// </summary>
        internal static string tbPatients {
            get {
                return ResourceManager.GetString("tbPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent *.
        /// </summary>
        internal static string tbPatientSt {
            get {
                return ResourceManager.GetString("tbPatientSt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string tbPhone {
            get {
                return ResourceManager.GetString("tbPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon *.
        /// </summary>
        internal static string tbPhoneS {
            get {
                return ResourceManager.GetString("tbPhoneS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mogući termini:.
        /// </summary>
        internal static string tbPossibleApps {
            get {
                return ResourceManager.GetString("tbPossibleApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bračni status.
        /// </summary>
        internal static string tbRelationship {
            get {
                return ResourceManager.GetString("tbRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum:.
        /// </summary>
        internal static string tbReportDate {
            get {
                return ResourceManager.GetString("tbReportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveštaj o zakazanim terminima.
        /// </summary>
        internal static string tbReportTitle {
            get {
                return ResourceManager.GetString("tbReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soba.
        /// </summary>
        internal static string tbRoom {
            get {
                return ResourceManager.GetString("tbRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprema sobe.
        /// </summary>
        internal static string tbRoomEq {
            get {
                return ResourceManager.GetString("tbRoomEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj sobe.
        /// </summary>
        internal static string tbRoomNum {
            get {
                return ResourceManager.GetString("tbRoomNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soba *.
        /// </summary>
        internal static string tbRoomS {
            get {
                return ResourceManager.GetString("tbRoomS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip sobe.
        /// </summary>
        internal static string tbRoomType {
            get {
                return ResourceManager.GetString("tbRoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nikola Nikolić, sekretar.
        /// </summary>
        internal static string tbSecretary {
            get {
                return ResourceManager.GetString("tbSecretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi.
        /// </summary>
        internal static string tbSelect {
            get {
                return ResourceManager.GetString("tbSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smena.
        /// </summary>
        internal static string tbShift {
            get {
                return ResourceManager.GetString("tbShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smena *.
        /// </summary>
        internal static string tbShiftS {
            get {
                return ResourceManager.GetString("tbShiftS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potpis:.
        /// </summary>
        internal static string tbSignature {
            get {
                return ResourceManager.GetString("tbSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specijalizacija.
        /// </summary>
        internal static string tbSpecialty {
            get {
                return ResourceManager.GetString("tbSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specijalizacija *.
        /// </summary>
        internal static string tbSpecialtyS {
            get {
                return ResourceManager.GetString("tbSpecialtyS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string tbSurname {
            get {
                return ResourceManager.GetString("tbSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime *.
        /// </summary>
        internal static string tbSurnameS {
            get {
                return ResourceManager.GetString("tbSurnameS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst obaveštenja *.
        /// </summary>
        internal static string tbText {
            get {
                return ResourceManager.GetString("tbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string tbTheme {
            get {
                return ResourceManager.GetString("tbTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov obaveštenja *.
        /// </summary>
        internal static string tbTitle {
            get {
                return ResourceManager.GetString("tbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID korisnika.
        /// </summary>
        internal static string tbUserId {
            get {
                return ResourceManager.GetString("tbUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godišnji odmor.
        /// </summary>
        internal static string tbVacation {
            get {
                return ResourceManager.GetString("tbVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аko dodajete više alergena odvojite ih zarezom..
        /// </summary>
        internal static string txtAddAllergies {
            get {
                return ResourceManager.GetString("txtAddAllergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavi novo obaveštenje.
        /// </summary>
        internal static string txtCreateNotification {
            get {
                return ResourceManager.GetString("txtCreateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite alergene:.
        /// </summary>
        internal static string txtEnterAllergies {
            get {
                return ResourceManager.GetString("txtEnterAllergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formiraj izveštaj.
        /// </summary>
        internal static string txtFormReport {
            get {
                return ResourceManager.GetString("txtFormReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gostujući nalozi.
        /// </summary>
        internal static string txtListOfGuests {
            get {
                return ResourceManager.GetString("txtListOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija.
        /// </summary>
        internal static string txtRegistration {
            get {
                return ResourceManager.GetString("txtRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži novi termin.
        /// </summary>
        internal static string txtSchedule {
            get {
                return ResourceManager.GetString("txtSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakazani pregledi.
        /// </summary>
        internal static string txtScheduledApps {
            get {
                return ResourceManager.GetString("txtScheduledApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži.
        /// </summary>
        internal static string txtShow {
            get {
                return ResourceManager.GetString("txtShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži.
        /// </summary>
        internal static string txtShow2 {
            get {
                return ResourceManager.GetString("txtShow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni.
        /// </summary>
        internal static string txtUpdate {
            get {
                return ResourceManager.GetString("txtUpdate", resourceCulture);
            }
        }
    }
}
