//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_IS.SecretaryView.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_sr_LATIN_CS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_sr_LATIN_CS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hospital_IS.SecretaryView.Localization.Strings.sr-LATIN-CS", typeof(Strings_sr_LATIN_CS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termini.
        /// </summary>
        internal static string btnAppointments {
            get {
                return ResourceManager.GetString("btnAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doktori.
        /// </summary>
        internal static string btnDoctors {
            get {
                return ResourceManager.GetString("btnDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjava.
        /// </summary>
        internal static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obaveštenja.
        /// </summary>
        internal static string btnNotifications {
            get {
                return ResourceManager.GetString("btnNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijenti.
        /// </summary>
        internal static string btnPatients {
            get {
                return ResourceManager.GetString("btnPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prostorije.
        /// </summary>
        internal static string btnRooms {
            get {
                return ResourceManager.GetString("btnRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        internal static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoć.
        /// </summary>
        internal static string heHelp {
            get {
                return ResourceManager.GetString("heHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        internal static string heLanguage {
            get {
                return ResourceManager.GetString("heLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacije.
        /// </summary>
        internal static string heOperations {
            get {
                return ResourceManager.GetString("heOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string heTheme {
            get {
                return ResourceManager.GetString("heTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaciji.
        /// </summary>
        internal static string miAbout {
            get {
                return ResourceManager.GetString("miAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna.
        /// </summary>
        internal static string miDark {
            get {
                return ResourceManager.GetString("miDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski jezik.
        /// </summary>
        internal static string miEnglish {
            get {
                return ResourceManager.GetString("miEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoć.
        /// </summary>
        internal static string miHelp {
            get {
                return ResourceManager.GetString("miHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svetla.
        /// </summary>
        internal static string miLight {
            get {
                return ResourceManager.GetString("miLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registruj korisnika.
        /// </summary>
        internal static string miRegistration {
            get {
                return ResourceManager.GetString("miRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži termin.
        /// </summary>
        internal static string miScheduling {
            get {
                return ResourceManager.GetString("miScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski jezik.
        /// </summary>
        internal static string miSerbian {
            get {
                return ResourceManager.GetString("miSerbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži.
        /// </summary>
        internal static string miShow {
            get {
                return ResourceManager.GetString("miShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni.
        /// </summary>
        internal static string miUpdate {
            get {
                return ResourceManager.GetString("miUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolnica Zdravo.
        /// </summary>
        internal static string tbHospital {
            get {
                return ResourceManager.GetString("tbHospital", resourceCulture);
            }
        }
    }
}
